version: '2.2'
services:

# https://github.com/vulhub/vulhub/tree/master/bash/shellshock
 shellshock:
   image: vulhub/bash:4.3.0-with-httpd
   container_name: shellshock
   ports:
    - "80"
   volumes:
    - ./bash/shellshock/safe.cgi:/var/www/html/safe.cgi
    - ./bash/shellshock/victim.cgi:/var/www/html/victim.cgi
   hostname: shellshock
   networks:
     vulhubnet:
       ipv4_address: 10.1.1.5

# https://github.com/vulhub/vulhub/tree/master/jenkins/CVE-2018-1000861
 jenkins:
   image: vulhub/jenkins:2.138
   container_name: jenkins
   init: true
   ports:
    - "50000"
    - "8080"
   hostname: jenkins
   networks:
     vulhubnet:
       ipv4_address: 10.1.1.6

# https://github.com/vulhub/vulhub/tree/master/log4j/CVE-2021-44228
 solr-log4j:
   image: vulhub/solr:8.11.0
   container_name: solr-log4j
   ports:
     - "8983"
   hostname: solr-log4j
   networks:
     vulhubnet:
       ipv4_address: 10.1.1.11
       
# https://github.com/vulhub/vulhub/tree/master/tomcat/tomcat8
 tomcat:
   image: vulhub/tomcat:8.0
   container_name: tomcat
   volumes:
    - ./tomcat/tomcat8/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    - ./tomcat/tomcat8/context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml
    - ./tomcat/tomcat8/context.xml:/usr/local/tomcat/webapps/host-manager/META-INF/context.xml
   ports:
     - "8080:8080"
   hostname: tomcat
   networks:
     vulhubnet:
       ipv4_address: 10.1.1.12
       
 kali:
   build: ./kali
   container_name: kali
   hostname: kali
   tty: true
   networks:
     vulhubnet:
       ipv4_address: 10.1.1.10

networks:
  vulhubnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.1.0/24
          gateway: 10.1.1.1

# docker network create --subnet=10.1.1.0/24 vulhubnet
#
# Add these entries to your /etc/hosts file:
#
# Vulhub lab
#10.1.1.5        shellshock
#10.1.1.6        jenkins
#10.1.1.7        phpmyadmin
#10.1.1.8        mysql
#10.1.1.9        telnetserver
#10.1.1.10       kali
#10.1.1.11       solr-log4j
#10.1.1.12       tomcat
